version: '3.7'

services:
  app:
    image: if3110-2023-02-36-client-spa:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
